# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coreBatch <- function(X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mu_beta_vb, sig2_beta_vb, tau_vb) {
    invisible(.Call(`_locus_coreBatch`, X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mu_beta_vb, sig2_beta_vb, tau_vb))
}

coreZBatch <- function(X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb, tau_vb) {
    invisible(.Call(`_locus_coreZBatch`, X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb, tau_vb))
}

coreProbitBatch <- function(X, W, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb) {
    invisible(.Call(`_locus_coreProbitBatch`, X, W, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb))
}

coreLoop <- function(X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind, c = 1) {
    invisible(.Call(`_locus_coreLoop`, X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind, c))
}

coreZLoop <- function(X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind, c = 1) {
    invisible(.Call(`_locus_coreZLoop`, X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind, c))
}

coreLogitLoop <- function(X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, psi_vb, sig2_beta_vb, shuffled_ind) {
    invisible(.Call(`_locus_coreLogitLoop`, X, Y, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, psi_vb, sig2_beta_vb, shuffled_ind))
}

coreProbitLoop <- function(X, W, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb, shuffled_ind) {
    invisible(.Call(`_locus_coreProbitLoop`, X, W, gam_vb, log_om_vb, log_1_min_om_vb, log_sig2_inv_vb, beta_vb, mat_x_m1, mat_z_mu, mu_beta_vb, sig2_beta_vb, shuffled_ind))
}

coreStructLoop <- function(X, Y, gam_vb, log_Phi_mu_theta_vb, log_1_min_Phi_mu_theta_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind) {
    invisible(.Call(`_locus_coreStructLoop`, X, Y, gam_vb, log_Phi_mu_theta_vb, log_1_min_Phi_mu_theta_vb, log_sig2_inv_vb, log_tau_vb, beta_vb, mat_x_m1, mu_beta_vb, sig2_beta_vb, tau_vb, shuffled_ind))
}

